variable "region" {
  description = "The region to deploy the VPC in eu-west-1"
  type        = string
  default     = "eu-west-1"
}

#------------------------------------------------------------------------------
# Misc
#------------------------------------------------------------------------------
variable "name_prefix" {
  description = "Name prefix for resources on AWS"
}

#------------------------------------------------------------------------------
# AWS Virtual Private Network
#------------------------------------------------------------------------------
variable "vpc_cidr_block" {
  description = "AWS VPC CIDR Block"
}

#------------------------------------------------------------------------------
# AWS Subnets
#------------------------------------------------------------------------------
variable "availability_zones" {
  type        = list(any)
  description = "List of availability zones to be used by subnets"
}

variable "public_subnets_cidrs_per_availability_zone" {
  type        = list(any)
  description = "List of CIDRs to use on each availability zone for public subnets"
}

variable "private_subnets_cidrs_per_availability_zone" {
  type        = list(any)
  description = "List of CIDRs to use on each availability zone for private subnets"
}

variable "single_nat" {
  type        = bool
  default     = false
  description = "enable single NAT Gateway"
}

variable "additional_tags" {
  default     = {}
  description = "Additional resource tags"
  type        = map(string)
}

variable "instance_type" {

  type = list(any)
}

variable "database_name" {
  description = "This is the rds database name"
  type        = string
}
variable "rds_username" {
  description = "This is the rds database user"
  type        = string

}
variable "rds_password" {
  description = "This is the rds database password and it will be stored in the secret manager"
  type        = string

}
variable "identifier" {
  description = "This is the rds instance identifier name "
  type        = string
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

# This the accountmircoservice-app application and its assocaiated env variables
variable "accountmircoservice-app" {}
variable "accountmircoservice-env" {}


# ## This the filemircoservice-app application and its assocaiated env variables 
variable "filemircoservice-app" {}
variable "filetmircoservice-env" {}


## This the filemircoservice-app application and its assocaiated env variables 
variable "jobmircoservice-app" {}
variable "jobmircoservice-env" {}


## This the statelessdatamircoservice-app application and its assocaiated env variables 
variable "statelessdatamircoservice-app" {}
variable "statelessdatamircoservice-env" {}



